In [34]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [35]:
from google.colab import drive
drive.mount('/content/drive')
!cp /content/drive/My\ Drive/Colab\ Notebooks/learning.datascience/test.csv .

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [36]:
nfl_frame = pd.read_csv('test.csv', sep='\t')

In [37]:
nfl_frame

   Rank                  Team     GP  ...   Pct.  First NFL Season   Division
0     1        Dallas Cowboys    914  ...  0.572              1960   NFC East
1     2     Green Bay Packers  1,368  ...  0.567              1921  NFC North
2     3  New England Patriots    916  ...  0.564              1960   AFC East
3     4         Chicago Bears  1,402  ...  0.563              1920  NFC North
4     5      Baltimore Ravens    384  ...  0.559              1996  AFC North
5     6        Miami Dolphins    832  ...  0.552              1966   AFC East

[6 rows x 9 columns]

In [38]:
nfl_frame.columns

Index(['Rank', 'Team', 'GP', 'Won', 'Lost', 'Tied', 'Pct.', 'First NFL Season',
       'Division'],
      dtype='object')

In [39]:
nfl_frame.Team

0          Dallas Cowboys
1       Green Bay Packers
2    New England Patriots
3           Chicago Bears
4        Baltimore Ravens
5          Miami Dolphins
Name: Team, dtype: object

In [40]:
nfl_frame[['Team', 'First NFL Season']]

                   Team  First NFL Season
0        Dallas Cowboys              1960
1     Green Bay Packers              1921
2  New England Patriots              1960
3         Chicago Bears              1920
4      Baltimore Ravens              1996
5        Miami Dolphins              1966

In [41]:
nfl_frame['First NFL Season']

0    1960
1    1921
2    1960
3    1920
4    1996
5    1966
Name: First NFL Season, dtype: int64

In [42]:
DataFrame(nfl_frame, columns=['Team', 'First NFL Season'])

                   Team  First NFL Season
0        Dallas Cowboys              1960
1     Green Bay Packers              1921
2  New England Patriots              1960
3         Chicago Bears              1920
4      Baltimore Ravens              1996
5        Miami Dolphins              1966

In [43]:
DataFrame(nfl_frame, columns=['Team', 'First NFL Season', 'Stadium'])

                   Team  First NFL Season  Stadium
0        Dallas Cowboys              1960      NaN
1     Green Bay Packers              1921      NaN
2  New England Patriots              1960      NaN
3         Chicago Bears              1920      NaN
4      Baltimore Ravens              1996      NaN
5        Miami Dolphins              1966      NaN

In [44]:
nfl_frame.head()

   Rank                  Team     GP  ...   Pct.  First NFL Season   Division
0     1        Dallas Cowboys    914  ...  0.572              1960   NFC East
1     2     Green Bay Packers  1,368  ...  0.567              1921  NFC North
2     3  New England Patriots    916  ...  0.564              1960   AFC East
3     4         Chicago Bears  1,402  ...  0.563              1920  NFC North
4     5      Baltimore Ravens    384  ...  0.559              1996  AFC North

[5 rows x 9 columns]

In [45]:
nfl_frame.head(3)

   Rank                  Team     GP  ...   Pct.  First NFL Season   Division
0     1        Dallas Cowboys    914  ...  0.572              1960   NFC East
1     2     Green Bay Packers  1,368  ...  0.567              1921  NFC North
2     3  New England Patriots    916  ...  0.564              1960   AFC East

[3 rows x 9 columns]

In [46]:
nfl_frame.tail()

   Rank                  Team     GP  ...   Pct.  First NFL Season   Division
1     2     Green Bay Packers  1,368  ...  0.567              1921  NFC North
2     3  New England Patriots    916  ...  0.564              1960   AFC East
3     4         Chicago Bears  1,402  ...  0.563              1920  NFC North
4     5      Baltimore Ravens    384  ...  0.559              1996  AFC North
5     6        Miami Dolphins    832  ...  0.552              1966   AFC East

[5 rows x 9 columns]

In [47]:
nfl_frame.tail(3)

   Rank              Team     GP  Won  ...  Tied   Pct.  First NFL Season   Division
3     4     Chicago Bears  1,402  769  ...    42  0.563              1920  NFC North
4     5  Baltimore Ravens    384  214  ...     1  0.559              1996  AFC North
5     6    Miami Dolphins    832  457  ...     4  0.552              1966   AFC East

[3 rows x 9 columns]

In [48]:
nfl_frame.iloc[3]

Rank                            4
Team                Chicago Bears
GP                          1,402
Won                           769
Lost                          591
Tied                           42
Pct.                        0.563
First NFL Season             1920
Division                NFC North
Name: 3, dtype: object

In [49]:
nfl_frame['Stadium'] = "Levi's Stadium"

In [50]:
nfl_frame

   Rank                  Team  ...   Division         Stadium
0     1        Dallas Cowboys  ...   NFC East  Levi's Stadium
1     2     Green Bay Packers  ...  NFC North  Levi's Stadium
2     3  New England Patriots  ...   AFC East  Levi's Stadium
3     4         Chicago Bears  ...  NFC North  Levi's Stadium
4     5      Baltimore Ravens  ...  AFC North  Levi's Stadium
5     6        Miami Dolphins  ...   AFC East  Levi's Stadium

[6 rows x 10 columns]

In [51]:
nfl_frame['Stadium'] = np.arange(6)

In [52]:
nfl_frame

   Rank                  Team     GP  ...  First NFL Season   Division  Stadium
0     1        Dallas Cowboys    914  ...              1960   NFC East        0
1     2     Green Bay Packers  1,368  ...              1921  NFC North        1
2     3  New England Patriots    916  ...              1960   AFC East        2
3     4         Chicago Bears  1,402  ...              1920  NFC North        3
4     5      Baltimore Ravens    384  ...              1996  AFC North        4
5     6        Miami Dolphins    832  ...              1966   AFC East        5

[6 rows x 10 columns]

In [53]:
stadiums = Series(["Livi's stadium", 'AT&T stadium'], index=[4,0])

In [54]:
stadiums

4    Livi's stadium
0      AT&T stadium
dtype: object

In [55]:
nfl_frame['Stadium'] = stadiums

In [56]:
nfl_frame

   Rank                  Team  ...   Division         Stadium
0     1        Dallas Cowboys  ...   NFC East    AT&T stadium
1     2     Green Bay Packers  ...  NFC North             NaN
2     3  New England Patriots  ...   AFC East             NaN
3     4         Chicago Bears  ...  NFC North             NaN
4     5      Baltimore Ravens  ...  AFC North  Livi's stadium
5     6        Miami Dolphins  ...   AFC East             NaN

[6 rows x 10 columns]

In [57]:
del nfl_frame['Stadium']

In [58]:
nfl_frame

   Rank                  Team     GP  ...   Pct.  First NFL Season   Division
0     1        Dallas Cowboys    914  ...  0.572              1960   NFC East
1     2     Green Bay Packers  1,368  ...  0.567              1921  NFC North
2     3  New England Patriots    916  ...  0.564              1960   AFC East
3     4         Chicago Bears  1,402  ...  0.563              1920  NFC North
4     5      Baltimore Ravens    384  ...  0.559              1996  AFC North
5     6        Miami Dolphins    832  ...  0.552              1966   AFC East

[6 rows x 9 columns]

In [59]:
data = {'City':['SF','LA','NYC'], 'Population':[837000,3880000,8400000]}

In [60]:
data

{'City': ['SF', 'LA', 'NYC'], 'Population': [837000, 3880000, 8400000]}

In [61]:
city_frame = DataFrame(data)

In [62]:
city_frame

  City  Population
0   SF      837000
1   LA     3880000
2  NYC     8400000